apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: woe-sim
  name: woe-sim
  namespace: woe-sim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: woe-sim
  template:
    metadata:
      labels:
        app: woe-sim
        actorSystemName: woe-sim
    spec:
      containers:
        - name: woe-sim
          image: mckeeh3/woe-sim
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            # akka-management and bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 1
              memory: 1Gi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_TOOL_OPTIONS
              value: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: postgresql_url
              valueFrom: { secretKeyRef: { name: postgresql-env, key: postgresql_url } }
            - name: postgresql_username
              valueFrom: { secretKeyRef: { name: postgresql-env, key: postgresql_username } }
            - name: postgresql_password
              valueFrom: { secretKeyRef: { name: postgresql-env, key: postgresql_password } }
            - name: woe_simulator_http_server_host
              value: "woe-sim-service.woe-sim.svc.cluster.local"
            - name: woe_simulator_http_server_port
              value: "8080"
            - name: woe_twin_http_server_host
              value: "woe-twin-service.woe-twin.svc.cluster.local"
            - name: woe_twin_http_server_port
              value: "8080"
            - name: woe_twin_telemetry_servers
              value: "woe.simulator.GrpcClient:woe-twin-service.woe-twin.svc.cluster.local:8081"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: woe-sim
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: woe-sim
subjects:
  # Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
  # For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
  - kind: User
    name: system:serviceaccount:woe-sim:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
